version: '2.1'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest

    env_file:
     - .env

    ports:
      - "15672:15672"
      - "5672:5672"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 3

  producer:
    image: com-github-nebtrx-microexample-producer:0.0.1-SNAPSHOT

    env_file:
      - .env

    depends_on:
      rabbitmq:
        condition: service_healthy


  webconsumer:
    image: com-github-nebtrx-microexample-webconsumer:0.0.1-SNAPSHOT

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:
      rabbitmq:
        condition: service_healthy

    links:
      - rabbitmq
